# version: '2'
# services:
#   php:
#     image: yiisoftware/yii2-php:7.4-apache
#     volumes:
#       - ~/.composer-docker/cache:/root/.composer/cache:delegated
#       - ./:/app:delegated
#     ports:
#       - '8000:80'


services:
  orphanage-kindness:
    restart: always
    container_name: orphanage-kindness
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html/
    ports:
      - '502:80'
    networks:
     - shared
    
networks:
  shared:
    name: shared-network
    external: true
